name: capstone_amazon_analytics
version: "1.0.0"
config-version: 2

profile: capstone_amazon_profile

########################################
# Paths
########################################
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

########################################
# Models configuration
########################################
models:
  capstone_amazon_analytics:

####################################
# Sources (External Tables)
# No materialization – metadata only
####################################
#sources:
#+schema: RAW
#+materialized: ephemeral

####################################
# Staging layer
# Clean & typed views
####################################
    staging:
      +schema: STAGE
      +materialized: view

####################################
# Mart layer
# Business-ready tables
####################################
    marts:
      +schema: MART         # means: final_schema = target.schema+ "_" + custom_schema  # target.schema is what we have written in profiles.yml
      +materialized: table    # So: staging = STAGE_STAGE , marts = MSTAGE_MART
