name: Terraform Destroy Manual

# Manual trigger only (no auto execution)
on:
  workflow_dispatch: # Enables "Run workflow" button in GitHub UI

permissions:
  id-token: write
  contents: read

jobs:
  terraform-destroy:
    name: Terraform Destroy (Manual)
    runs-on: ubuntu-latest

    # Require environment approval to prevent accidental destroy
    environment:
      name: dev-approve # Make sure this environment exists in GitHub > Settings > Environments

    steps:
    # Step 1: Checkout code
      - name: Checkout source code
        uses: actions/checkout@v3

    # Step 2: Configure AWS credentials via OIDC
      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
         role-to-assume: arn:aws:iam::<your-account-id>:role/github-oidc-role
         aws-region: eu-central-1

    # Step 3: Setup Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

    # Step 4: Initialize Terraform backend
      - name: Terraform Init
        run: terraform init
        working-directory: ./infra

    # Step 5: Run Terraform Destroy (manual approval required)
      - name: Terraform Destroy (Dangerous Operation)
        run: terraform destroy -auto-approve -input=false
        working-directory: ./infra

