
version: 2

models:
  - name: dim_products
    description: "Product dimension table"

    columns:
      - name: product_id
        description: "Primary key of the product dimension"
        tests:
          - not_null
          - unique
      - name: categories
        description: "Main product category"

  - name: fct_reviews
    description: "Fact table containing individual product reviews"

    columns:
      
      - name: product_id
        description: "Foreign key to dim_products"
        tests:
          - not_null
          - relationships:
              to: ref('dim_products')
              field: product_id

      - name: avg_rating
        description: "Averagerating score"
        tests:
          - not_null
          
      - name: review_count
        description: "Number of reviews"
        tests:
          - not_null

models:
  - name: fct_reviews_granular
    columns:
      - name: review_id
        tests:
          - not_null
          - unique

      - name: product_id
        tests:
          - not_null

      - name: rating
        tests:
          - not_null


models:
  - name: dim_date
    columns:
      - name: date_day
        tests:
          - not_null
          - unique

models:
  - name: mart_product_kpi
    columns:
      - name: product_id
        tests:
          - not_null
          - unique

      - name: review_count
        tests:
          - not_null

      - name: avg_rating
        tests:
          - not_null

      - name: first_review_date
        tests:
          - not_null

models:
  - name: mart_avg_rating_by_year_brand
    columns:
      - name: brand
        tests:
         - not_null
      - name: review_year
        tests:
          - not_null
